# Generated by Django 4.2.3 on 2024-02-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_myorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myorder',
            name='cash_payment',
        ),
        migrations.RemoveField(
            model_name='myorder',
            name='stripe_payment',
        ),
        migrations.AddField(
            model_name='myorder',
            name='payment_method',
            field=models.CharField(default='cash', max_length=40),
        ),
    ]
