# Generated by Django 4.2.3 on 2024-02-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_myorder_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=8),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=8),
        ),
    ]
