# Generated by Django 4.2.3 on 2024-02-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_myorder_quantity_alter_myorder_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=8),
        ),
    ]
