# Generated by Django 4.2.3 on 2024-02-03 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_myorder_date_myorder_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
