# Generated by Django 4.2.3 on 2024-02-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_myorder_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='price',
            field=models.IntegerField(),
        ),
    ]
