# Generated by Django 4.2.3 on 2024-02-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_myorder_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='food_item_name',
            field=models.TextField(max_length=100),
        ),
    ]
