# Generated by Django 4.2.3 on 2024-02-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_myorder_food_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
