# Generated by Django 4.2.3 on 2024-02-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_myorder_food_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='price',
            field=models.IntegerField(),
        ),
    ]
