# Generated by Django 4.2.3 on 2024-02-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_myorder_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='price',
            field=models.IntegerField(default='1'),
        ),
    ]
