# Generated by Django 4.2.3 on 2024-02-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_myorder_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='quantity',
            field=models.CharField(max_length=40),
        ),
    ]
