# Generated by Django 4.2.3 on 2024-02-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_myorder_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='price',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='quantity',
            field=models.CharField(max_length=400),
        ),
    ]
