# Generated by Django 4.2.3 on 2024-03-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_deliveryperson_myorder_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryperson',
            name='profile_pic',
            field=models.ImageField(default='photo', upload_to='profile_pic/'),
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='vehicle_number',
            field=models.CharField(default='go01xx1234', max_length=100),
        ),
    ]
