# Generated by Django 4.2.3 on 2024-03-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_deliveryperson_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryperson',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_pic/'),
        ),
        migrations.AlterField(
            model_name='deliveryperson',
            name='vehicle_number',
            field=models.CharField(max_length=100),
        ),
    ]
