# Generated by Django 4.2.3 on 2024-03-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_deliveryperson_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'customer'), ('manager', 'manager')], default='customer', max_length=10),
        ),
    ]
