# Generated by Django 4.2.3 on 2024-03-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='food_item_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='price',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='quantity',
            field=models.TextField(),
        ),
    ]
