# Generated by Django 4.2.3 on 2024-03-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_myorder_food_item_name_alter_myorder_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='food_item_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='price',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='quantity',
            field=models.CharField(max_length=400),
        ),
    ]
