# Generated by Django 4.2.3 on 2024-04-17 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_myorder_food_item_name_alter_myorder_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='booking_fee',
        ),
    ]
