# Generated by Django 4.2.3 on 2024-04-24 06:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_remove_reservation_booking_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
