# Generated by Django 4.2.3 on 2024-04-24 06:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
